import { test } from "node:test";
import assert from "node:assert/strict";

const { buildCandidates, looksHashed, escapeAttr, escapeIdent } = await import(
  "../src/browser/selector.ts"
);
const { normalizeRef, handleDialog } = await import("../src/browser/explore.ts");

/**
 * PURE selector-derivation logic (no browser). It is the bridge to the lint: the
 * exploration tools return real CSS, never refs. Here we validate priority, the "hashed"
 * heuristic and that an ephemeral ref or role+name notation from the snapshot is NEVER emitted.
 */

test("looksHashed: discards autogenerated tokens, accepts stable names", () => {
  // Hashed
  for (const t of ["css-1a2b3c", "sc-bdVaJa", "jsx-123456", "a1b2c3d4e5", "12345", "x9f8e7d6c5"]) {
    assert.equal(looksHashed(t), true, `${t} should be hashed`);
  }
  // Stable
  for (const t of ["search-button", "MuiButton-root", "header", "nav", "btn-primary", "q"]) {
    assert.equal(looksHashed(t), false, `${t} should be stable`);
  }
});

test("buildCandidates: respects the priority id → testid → name → aria-label", () => {
  const cands = buildCandidates({
    tag: "input",
    id: "search-box",
    name: "q",
    ariaLabel: "Search",
    testId: "search-input",
    classes: ["form-control"],
  });
  assert.equal(cands[0], "#search-box");
  assert.equal(cands[1], '[data-testid="search-input"]');
  assert.equal(cands[2], 'input[name="q"]');
  assert.equal(cands[3], '[aria-label="Search"]');
});

test("buildCandidates: ignores hashed id/classes and falls back to stable attributes", () => {
  const cands = buildCandidates({
    tag: "button",
    id: "css-1a2b3c",
    ariaLabel: "Send",
    classes: ["sc-bdVaJa", "submit-btn"],
  });
  assert.ok(!cands.some((c) => c.includes("css-1a2b3c")), "must not use a hashed id");
  assert.ok(!cands.some((c) => c.includes("sc-bdVaJa")), "must not use a hashed class");
  assert.ok(cands.includes('[aria-label="Send"]'));
  assert.ok(cands.includes("button.submit-btn"));
});

test("buildCandidates: NEVER emits ephemeral refs or role+name notation", () => {
  const cands = buildCandidates({
    tag: "a",
    name: "link",
    ariaLabel: 'See more "details"',
    role: "link",
    classes: ["nav-link"],
  });
  for (const c of cands) {
    assert.ok(!/aria-ref/.test(c), `candidate must not be aria-ref: ${c}`);
    assert.ok(!/^\s*[a-zA-Z][\w-]*\s+["']/.test(c), `candidate must not be role+name: ${c}`);
  }
});

test("escapeAttr: escapes quotes so as not to break [attr=\"...\"]", () => {
  assert.equal(escapeAttr('See "more"'), 'See \\"more\\"');
  const cands = buildCandidates({ tag: "a", ariaLabel: 'See "more"' });
  assert.ok(cands.includes('[aria-label="See \\"more\\""]'));
});

test("buildCandidates: dedups candidates", () => {
  const cands = buildCandidates({ tag: "div", classes: ["x", "x"] });
  assert.equal(new Set(cands).size, cands.length);
});

test("buildCandidates: combines type+placeholder and keeps the placeholder alone", () => {
  const cands = buildCandidates({ tag: "input", type: "search", placeholder: "Search..." });
  assert.ok(cands.includes('input[type="search"][placeholder="Search..."]'));
  assert.ok(cands.includes('input[placeholder="Search..."]'));
  // the type+placeholder combo must come before the placeholder alone
  assert.ok(
    cands.indexOf('input[type="search"][placeholder="Search..."]') <
      cands.indexOf('input[placeholder="Search..."]'),
  );
});

test("buildCandidates: role is the last resort (after stable classes)", () => {
  const cands = buildCandidates({ tag: "div", role: "button", classes: ["cta"] });
  assert.ok(cands.includes('div[role="button"]'));
  assert.ok(cands.indexOf("div.cta") < cands.indexOf('div[role="button"]'));
});

test("buildCandidates: with no useful attributes returns an empty list (falls back to a structural path)", () => {
  // Only hashed classes + no id/name/aria → nothing stable to offer.
  const cands = buildCandidates({ tag: "span", id: "css-9f8e7d", classes: ["jsx-12345"] });
  assert.deepEqual(cands, []);
});

test("looksHashed: names with short digits are NOT discarded (h1, col-2, etc.)", () => {
  for (const t of ["h1", "h2", "col-2", "btn-2"]) {
    assert.equal(looksHashed(t), false, `${t} should be stable`);
  }
});

test("looksHashed: exact threshold of the long letter+digit mix (7 vs 8 chars)", () => {
  // 'xyz' avoids the hex clause (x,y,z aren't hex) to isolate the long-mix one {8,}.
  assert.equal(looksHashed("xyz1234"), false, "7 mixed chars: stable");
  assert.equal(looksHashed("xyz12345"), true, "8 mixed chars: hashed");
});

test("looksHashed: css-in-js prefixes WITHOUT hex isolate that clause", () => {
  assert.equal(looksHashed("emotion-cache"), true);
  assert.equal(looksHashed("styled-box"), true);
});

test("escapeIdent: escapes special characters (Tailwind-style selectors)", () => {
  assert.equal(escapeIdent("md:flex"), "md\\:flex");
  const cands = buildCandidates({ tag: "div", classes: ["md:flex"] });
  assert.ok(cands.includes("div.md\\:flex"));
});

test("normalizeRef: accepts e5 / ref=e5 / [ref=e5] and trims spaces", () => {
  assert.equal(normalizeRef("e5"), "e5");
  assert.equal(normalizeRef("ref=e5"), "e5");
  assert.equal(normalizeRef("[ref=e5]"), "e5");
  assert.equal(normalizeRef("  e12  "), "e12");
});

test("normalizeRef: does NOT reinterpret substrings as refs (frame5, theme5)", () => {
  assert.equal(normalizeRef("frame5"), "frame5", "must not return 'e5'");
  assert.equal(normalizeRef("theme5"), "theme5");
  assert.equal(normalizeRef("basura"), "basura"); // no match: input as-is (failure visible downstream)
});

test("handleDialog: changes the policy and by default does not hang (accept)", () => {
  const dismiss = handleDialog(false);
  assert.equal(dismiss.ok, true);
  assert.equal(dismiss.policy, "dismiss");
  const accept = handleDialog(true, "hi");
  assert.equal(accept.policy, "accept");
});
