/**
 * Derivation of robust CSS selectors for exploration (bridge to the lint/distiller).
 *
 * The exploration tools interact with the page via the ephemeral `ref` from the a11y snapshot
 * (`aria-ref=eN`), but a `ref` CANNOT be persisted in a tool: it gets invalidated on the next
 * mutation, and the lint ([memory/lint.ts]) rejects anything that isn't real CSS. That's why
 * each `bm_click`/`bm_type` resolves the node to a **stable CSS selector** and returns it to
 * the agent so it builds the narration with CSS, not with refs.
 *
 * This module is the PURE logic (no DOM): given the "signature" of an element (attributes we
 * read on the page), it produces an ORDERED list of candidate selectors by priority. The
 * browser module ([browser/explore.ts]) does two things on the page: (1) reads the signature,
 * (2) picks the first candidate that matches EXACTLY one element. So the testable part
 * (priority + "hashed" heuristic + escaping) lives here, without needing a browser.
 */

/** Attributes of an element useful to build a selector. */
export interface ElementSig {
  tag: string;
  id?: string;
  name?: string;
  ariaLabel?: string;
  /** data-testid / data-test-id / data-test / data-qa (the first one present). */
  testId?: string;
  role?: string;
  type?: string;
  placeholder?: string;
  classes?: string[];
}

/**
 * Does the token (id or class) look auto-generated by a bundler/CSS-in-js? Those change on
 * every build → a selector that uses them is fragile. Conservative heuristic: discard pure
 * numbers, long hex chunks, long letter+digit mixes, and typical CSS-in-js prefixes.
 */
export function looksHashed(token: string): boolean {
  if (!token) return true;
  if (/^[0-9]+$/.test(token)) return true; // purely numeric id/class
  if (/(^|[-_])[a-f0-9]{6,}([-_]|$)/i.test(token)) return true; // hex chunk (css-1a2b3c, sc-bdVaJa…)
  if (/[a-z]/i.test(token) && /[0-9]/.test(token) && /[a-z0-9]{8,}/i.test(token)) return true; // long mix
  if (/^(css|sc|jsx|emotion|styled)-/i.test(token)) return true; // css-in-js prefixes
  return false;
}

/** Escapes a value to use it inside `[attr="..."]`. */
export function escapeAttr(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Escapes an id/class for a `#id` / `.class` selector (a subset of CSS.escape, enough here). */
export function escapeIdent(value: string): string {
  return value.replace(/([^a-zA-Z0-9_-])/g, "\\$1");
}

/**
 * Builds the candidate selectors in order of preference. The caller tries each one against
 * the DOM and keeps the first that is UNIQUE. If none is unique, it falls back to a structural
 * path (built by explore.ts on the page). Priority: stable id → data-testid → name →
 * aria-label → type+placeholder → stable class → role.
 */
export function buildCandidates(sig: ElementSig): string[] {
  const out: string[] = [];
  const tag = (sig.tag || "*").toLowerCase();

  if (sig.id && !looksHashed(sig.id)) out.push(`#${escapeIdent(sig.id)}`);
  if (sig.testId) out.push(`[data-testid="${escapeAttr(sig.testId)}"]`);
  if (sig.name) out.push(`${tag}[name="${escapeAttr(sig.name)}"]`);
  if (sig.ariaLabel) out.push(`[aria-label="${escapeAttr(sig.ariaLabel)}"]`);
  if (sig.type && sig.placeholder) {
    out.push(`${tag}[type="${escapeAttr(sig.type)}"][placeholder="${escapeAttr(sig.placeholder)}"]`);
  }
  if (sig.placeholder) out.push(`${tag}[placeholder="${escapeAttr(sig.placeholder)}"]`);
  for (const c of sig.classes ?? []) {
    if (!looksHashed(c)) out.push(`${tag}.${escapeIdent(c)}`);
  }
  if (sig.role) out.push(`${tag}[role="${escapeAttr(sig.role)}"]`);

  // Dedup preserving order.
  return [...new Set(out)];
}
